language: haxe

os:
  - linux

haxe:
  - "3.4.7"
  - "4.0.0-rc.5"
  - development

matrix:
  allow_failures:
    - haxe: "3.4.7"
    - haxe: "development"

branches:
  only:
  - master
  - r2

install:
  - haxelib install hxnodejs
  - haxelib dev three.hx .

script:
  #- haxe build.hxml
  - haxe haxedoc.hxml
  - haxe test.hxml
  # TODO: run tests
